### ISSUE TITLE
Proposal

### ISSUE THREAD

**Issue by vikram-rawat** [moodymudskipper/typed#2]
I couldn't pass the temptation to try the package out. I just did a few benchmarks this morning... I thought of directly passing the datatype to rcpp and taking advantage of the c++ code already written. But it turns out to be that the overhead of leaving the R is more than it is supposed to be. I am not sure why is it so but this package is faster than baseR. and it is smaller in memory too...

``` r
library(Rcpp)
library(typed)
#> 
#> Attaching package: 'typed'
#> The following object is masked from 'package:utils':
#> 
#>     ?
cppFunction(code =
"NumericVector NumVec(NumericVector &x) {
    return(x);
 }
")

fcpp <- function(a, b){
  a <- NumVec(a)
  b <- NumVec(b)
  return(
    sum(a, b)
  )
}

fbase <- function(a, b){
  if(
    is.numeric(a) &&
    is.numeric(b)  
  ){
    return(
      sum(a, b)
    )
  }else{
    stop()
  }
}

ftyped <- function(a = ?numeric, b =?numeric ){
  return(
    sum(a,b)
  )
}

object.size(fcpp)
#> 7672 bytes
object.size(fbase)
#> 12512 bytes
object.size(ftyped)
#> 5336 bytes

microbenchmark::microbenchmark(
  ftyped(10,20),
  fbase(10,20),
  fcpp(10,20),
  times = 1e3
)
#> Unit: nanoseconds
#>            expr  min   lq    mean median   uq     max neval
#>  ftyped(10, 20)  700  800  2828.4    800  900 1919400  1000
#>   fbase(10, 20)  900 1000  5296.0   1100 1200 4110900  1000
#>    fcpp(10, 20) 3800 4200 11279.8   5600 6300 3494100  1000
```

<sup>Created on 2020-10-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by vikram-rawat** [comment]
1. I propose changing the `?` symbol to %typ% for more readable function. 
2. How would we pass default argument for the function is something that has to be looked into

**Comment by vikram-rawat** [comment]
I propose changing the `?` symbol to %typ% for more readable functions.

**Comment by moodymudskipper** [comment]
Hi Vikram, ftype here doesn't use {typed}, you need to start with a `?` on the left.

`?`has unary and binary syntax, and the lowest precedence. `%typ%` cannot be used as a drop in replacement.

Unrelated but your post makes me think that using {typed} syntax or a variant  to translate directly into C or cpp could be done, at least for basic cases, but it's another can of worms :).

**Comment by vikram-rawat** [comment]
Rcpp can even allow you to accept a function and return a function. I tried today. But I couldn't figure out how to set a return type in between.  I might have to look a little deeper for that. My idea was to create a variant for each data type of Rcpp from scalar to vector and directly let it pass.

But if it doesn't bring any speed up. Its useless to go to C. If your method is faster and easy than Its better to stick to it.

**Comment by vikram-rawat** [comment]
![Screenshot_2020-10-18-21-21-13-570_cn wps moffice_eng](https://user-images.githubusercontent.com/22342596/96373113-f8f51300-1187-11eb-8d25-21b923cac616.jpg)


These are the data types that might enter into R language... We should name our data types accordingly for sake of readability...

**Comment by vikram-rawat** [comment]
Just by adding that `?` I mean just by calling typed package function has a huge overhead.

```
> microbenchmark::microbenchmark(
+   ftyped(10,20),
+   fbase(10,20),
+   fcpp(10,20),
+   times = 1e3
+ )
Unit: nanoseconds
           expr   min       lq       mean median       uq     max neval
 ftyped(10, 20) 98401 105350.5 125218.207 110901 131051.5 4405701  1000
  fbase(10, 20)   700    901.0   1322.797   1101   1302.0   29202  1000
   fcpp(10, 20)  3101   4100.0   5348.387   4901   5801.0   29002  1000
```
In this scenario, all of a sudden base became a number one choice.

**Comment by moodymudskipper** [comment]
It's not necessarily that huge, the mean overhead is `0.000125` seconds, it means you can run it 10.000 times before waiting for a second, that's better than I thought it'd be tbh :). This might be optimized a bit but it's not really my concern.

These are also not equivalent, your base and cpp code just check once, with typed variables are protected throughout all the code.

If you want to control a user input in shiny for instant, `.1 ms` is OK.

**Comment by moodymudskipper** [comment]
Package will be made a bit more performant in iteration 3, we'll see by then if it makes sense to use C / C++.

Adressing the worry about  "?" : With iteration3, the code of the function will not contain `?` anymore, though the programmer will be able to use it to program as in iteration2. This will avoid some overheads, and the fact that calls to `?` don't print nicely.
