### ISSUE TITLE
Question on how to add more formula rules

### ISSUE THREAD

**Issue by ltuijnder** [moodymudskipper/typed#28]
Hi, I have a question on how I could add multiple formula assertion rules to my type.

For example, I have an integer and I want to impose some ranges on it its values. I would handle this as follows:
```
Integer(length = 1, null_ok = FALSE, "needs to be large enough" ~ . >= 3, "but not too large"~ . <= 10 )  ? x
```

But what if I want to have these 2 rules to be applied to a vector of any length:
```
Integer(null_ok = FALSE, "needs to be large enough" ~all( . >= 3), "but not too large"~ all(. <= 10))  ? x
> Error: 'language' object cannot be coerced to type 'integer'
```
An error is thrown because my formula is now assigned to the argument `length`. In your README you mentioned that you could also just directly assign the formula to `...`. However, this works only for 1 formula no?

Eg.  I cannot specify the following:
```
Integer(... = c("needs to be large enough" ~ all(. >= 3), "but not too large"~ all(. <= 10)) )  ? x
>Error in process_assertion_factory_dots(...) : 
>   assertions should be either named function, or unnamed formulas
Integer(... = list("needs to be large enough" ~ all(. >= 3), "but not too large"~ all(. <= 10)))  ? x
>Error in process_assertion_factory_dots(...) : 
>  assertions should be either named function, or unnamed formulas
```

The only workaround I currently see is to define all the rules that I want to apply dynamically to my type to define them in 1 function.
Which is not the nicest as I then do not get my custom error messages anymore..

Am I missing something obvious? 
Thanks for the nice package anyway :)

**Comment by moodymudskipper** [comment]
Hi and sorry for the late answer.

There are 2 ways to do it, first you might feed an empty argument to `length()`

``` r
library(typed, w = F)
Integer(,null_ok = FALSE, "needs to be large enough" ~all( . >= 3), "but not too large"~ all(. <= 10))  ? x 
x <- 1:15
#> Error: needs to be large enough
#> `all(value >= 3)`: FALSE
#> `expected`:        TRUE
x <- 7:15
#> Error: but not too large
#> `all(value <= 10)`: FALSE
#> `expected`:         TRUE
x <- 3:5
x
#> [1] 3 4 5
```

The other way is to use `...`

```r
Integer(null_ok = FALSE, ... = "needs to be large enough" ~all( . >= 3), ... = "but not too large"~ all(. <= 10))  ? y
y <- 1:15
#> Error: needs to be large enough
#> `all(value >= 3)`: FALSE
#> `expected`:        TRUE
y <- 7:15
#> Error: but not too large
#> `all(value <= 10)`: FALSE
#> `expected`:         TRUE
y <- 3:5
y
#> [1] 3 4 5
```

<sup>Created on 2022-11-06 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by ltuijnder** [comment]
Ooh I did not know that you could use `...` multiple times. Thanks. I learned something new today. This indeed neatly solves the issues in my eyes.
