### ISSUE TITLE
Failing on rcmdchecks when assign variables

### ISSUE THREAD

**Issue by latot** [moodymudskipper/typed#33]
Hi, other test, I wait some time to be able to reduce this in a simpler one, still I don't have idea why this happens.

[bug_typed.zip](https://github.com/moodymudskipper/typed/files/12601353/bug_typed.zip)

Basically, code and assertions inside the lib works, at least when you call a lib or similar, but when running tests it fails:

```R
> rcmdcheck::rcmdcheck()
[ FAIL 1 | WARN 0 | SKIP 0 | PASS 0 ]

══ Failed tests ════════════════════════════════════════════════════════════════
── Error ('test-bug_typed.R:4:3'): test_assert ─────────────────────────────────
Error: In `test_assert()` at `custom_var <- ...`:
could not find function "cassert"
Backtrace:
    ▆
 1. ├─bugtyped::test_assert() at test-bug_typed.R:4:2
 2. └─typed (local) `<fn>`(base::quote(1))

[ FAIL 1 | WARN 0 | SKIP 0 | PASS 0 ]
Error: Test failures
Execution halted

1 error ✖ | 1 warning ✖ | 0 notes ✔
```

Change a little on the code, and the test can pass, but no idea why, when assigning inside a function  variable this happens.

Thx!

**Comment by moodymudskipper** [comment]
Interesting, this seems like an issue about environments, for some reason in the env were the test are run, `?` cannot find `casser()`, which means it looks at the wrong place.

That upsets me that there are several environment issues with the package so think I'll work on it soon. Thanks so much for holding on.

**Comment by latot** [comment]
Hi, I found something very peculiar on R libraries, the issue is here: https://community.rstudio.com/t/weird-execution-files-on-library-elements-not-found/174194

If this is what is causing this, would be pretty important to write it on the docs.

**Comment by latot** [comment]
I have checked it, is not affected by https://github.com/moodymudskipper/typed/issues/43

This one of the blocking bugs actually.

**Comment by moodymudskipper** [comment]
I know, the environment bugs are the priority, these have nothing to do with file order.

**Comment by moodymudskipper** [comment]
I cannot reproduce this, I've put this in a package and the casser() function is found just fine

**Comment by latot** [comment]
@moodymudskipper  how do you execute it? to reproduce this example you must execute ```rcmdcheck::rcmdcheck()```, this issue happens when you run tests on the lib.

**Comment by moodymudskipper** [comment]
You are right sorry, I was running the tests

**Comment by moodymudskipper** [comment]
Hi @latot please tell me if you have other issues, for the provided package this fixes it on my side
