### ISSUE TITLE
Special case Inf

### ISSUE THREAD

**Issue by latot** [moodymudskipper/typed#34]
Hi all! here again, I was thinking that would be great have an option like ```inf_ok``` for numeric values and a special ```Inf``` value.

The problem here, is that every type has its own values, but there is some special value cases, NA, NULL, Inf.

Actually Inf can exists in any numeric value (in theory), but in R, ```Inf``` is a double type, there is no ```Inf``` in the integers, usually this is not a problem on R, because there is no strong types, but with ```typed``` I think is necessary have a proper ```Inf``` value for every numeric type, or just use something that is Inf but saves the type and use that info to compare later.

Obvs there is some.... weird things about the Inf.... I think one important question about a ```Inf``` type is when you compare two of them.

```Inf (integer)``` is equal to ```Inf (float)```?

There is at least, two ways to do this comparisons, one is in math theory, which should be FALSE, but I know some ppl will try to compare them in a different way, wanted to get the answer of TRUE, this will depends on the context of what are you asking, but thinking you are doing all right this comparison should never happen, because you should never compare integer with float.

I have more infinite integer blooms than more float blooms? the answer is FALSE
I have blooms, for some reason one var is in float (wrong type) and the other is in integer, both are the same blooms, which is bigger? they are equal.

Maybe the best answer is just, can't compare two inf of different types, block it!.

This comes with the question of the value of ```1/Inf``` which maybe depends on the type, I just don't know the right answer there.

Seems ```Inf``` is a headache when trying to use strong types, without be able to mix types for safe use, I think R needs a more robust ```Inf```.

Thx!

**Comment by moodymudskipper** [comment]
I think it's typically a case that is too niche to be implemented out of the box.

Here's how you might do it:

``` r
library(typed)
#> 
#> Attaching package: 'typed'
#> The following object is masked from 'package:utils':
#> 
#>     ?
Integerish <- function(length, null_ok = FALSE, ...) {
  if (missing(length)) {
    Double(, null_ok, "Expected integerish double or Inf" ~ rlang::is_integerish(value))
  } else {
    Double(length , null_ok, "Expected integerish double or Inf" ~ rlang::is_integerish(value))
  }
}

Integerish() ? x <- 1
Integerish() ? x <- 1.5
#> Error: Expected integerish double or Inf
#> `rlang::is_integerish(value)`: FALSE
#> `expected`:                    TRUE
Integerish() ? x <- Inf
```

I don't love the special casing for missing length, this can probably be fixed

**Comment by moodymudskipper** [comment]
You can also define your own assertion factory, though it's probably overkill for this case, for this you need to look into the code and take inspiration there.

https://github.com/moodymudskipper/typed/blob/master/R/06_native_types.R

For instance modifying `Double()` : 

```
Integerish <- as_assertion_factory(function(value, length, null_ok = FALSE) {
  if(null_ok && is.null(value)) return(NULL)
  if(!rlang::is_integerish(value)) {
    e <- sprintf(
      "%s\n%s",
      "type mismatch",
      waldo::compare(
        FALSE,
        TRUE,
        x_arg = "rlang::is_integerish(value)",
        y_arg = "expected"))
    stop(e, call. = FALSE)
  }
  if(!missing(length) && length(value) != length) {
    length <- as.integer(length)
    e <- sprintf(
      "%s\n%s",
      "length mismatch",
      waldo::compare(
        length(value),
        length,
        x_arg = "length(value)",
        y_arg = "expected"))
    stop(e, call. = FALSE)
  }
  value
})

Integerish() ? x <- 1
Integerish() ? x <- 1.5
Integerish() ? x <- Inf
```
