### ISSUE TITLE
Document good consistent style

### ISSUE THREAD

**Issue by latot** [moodymudskipper/typed#35]
Hi all again!, here again, after some time using this, at least for scripts it works great.

I think an improvement would be found a way to do some syntax more user friendly.

We actually have 3 types of types:

- Provided by typed lib
- Custom assertions
- Types declared based on assertions

```R
#I'm a integer from typed
typed::Integer() ? x

custom_assert <- typed::as_assertion_factory(function(value) {
  #I'm a useless assert of integer
  typed::Integer()
})

#I'm a custom assert
custom_assert() ? x

#set a static type
integer_t <- Integer()

#I'm a static integer
integer_t ? x
```

My point is the difference between the first two cases, with the last one.

I think the base, would be found a way, to declare all of them in the same way, all like ```assert() ?``` or all as ```assert ?```.

For small projects with not too much types is not a problem, but when using a lot of types, with bigger project, have all the ways to have the same syntax, would be great.

Thx!

**Comment by moodymudskipper** [comment]
I agree that the discrepancies in the style can be confusing, but they can be mitigated with some guidelines regarding inheritance.

I think `as_assertion_factory` is basically for expert use when we want to tweak error messages, and then you need to inspect the package code and know what you're doing. But most users don't need to use it.

We should document the simpler ways to do things. I don't think there's a need for a new feature.

```
library(typed)

# bad style, assertion factories are confused with assertions, syntax looks inconsistent
ScalarInteger <- Integer(1)
ScalarInteger ? x <- 1L

# good style 1
# inherit from Integer, set 1 parameter leave the rest flexible
ScalarInteger <- function(null_ok = FALSE, ...) Integer(1, null_ok, ...)
ScalarInteger() ? x <- 1L 
ScalarInteger(null_ok = TRUE) ? x <- NULL

# good style 2
# inherit from Integer but fix all arguments
ScalarInteger <- function() Integer(1)
ScalarInteger() ? x <- 1L 
```

Define a completely new type without `as_assertion_factory()`, by inheriting from `Any()` (or a more restricted type when it makes sense)

```
library(typed)
#> 
#> Attaching package: 'typed'
#> The following object is masked from 'package:utils':
#> 
#>     ?
Ggplot <- function() {
  # we can also define helper functions here if needed
  Any(, "Not a 'ggplot' object" ~ ggplot2::is.ggplot(value))
}

# fails as expected
Ggplot() ? x <- 1L
#> Error: Not a 'ggplot' object
#> `ggplot2::is.ggplot(value)`: FALSE
#> `expected`:                  TRUE

# works
Ggplot() ? x <- ggplot2::ggplot(cars, ggplot2::aes(speed, dist))
```

**Comment by latot** [comment]
Hi!, I think you are right, this issue could be just, adjust the docs, explain the issue, and best practices to use it :)

**Comment by moodymudskipper** [comment]
Follow up in #53
