### ISSUE TITLE
Function assertion fails when function returns with "return"

### ISSUE THREAD

**Issue by latot** [moodymudskipper/typed#36]
Oks, too hard to explain with words! Here the reduced example:

```R
library(typed)
f <- typed::Function() ? function(){
  function() {
    return()
  }
}
Error in x[[2]] : subscript out of bounds
```

If you return with a value instead of the keyword ```return``` it works.

Thx!

**Comment by moodymudskipper** [comment]
Interesting, I suppose I search for every return call in the function without discarding irrelevant ones.

Irrelevant ones would be trapped into quoting functions such as `quote()`, `quote()`, and `function()` itself. The latter case is what we find here and probably the only practical one. I think we can assume that `quote(return())` is a rare occurence but the case above is worth fixing.

**Comment by latot** [comment]
Yes, well this is the reduced example, the real one, is practical :3

Thx!
