### ISSUE TITLE
Update documentation about files naming and order when working in a Library

### ISSUE THREAD

**Issue by latot** [moodymudskipper/typed#43]
Well, I was playing again with the lib, and I found something very particular, that I think needs to be included in the documentation.

https://community.rstudio.com/t/weird-execution-files-on-library-elements-not-found/174194

Basically, when R loads a library, read and load the R/* files in alphabet order.

Pick this example:

file ```a.R``` has a function that uses types.
file ```b.R``` has the types used in ```a.R```

This library will fails, because R will first load ```a.R``` and then ```b.R```, how the types does not exists when the function is load will fail saying the variables/functions does not exists.

This very unusual on R, because how the expresions are not evaluated until they are called, you can load the files in any order, when you run tests all the functions will be already loaded and will works.

But with types is not the same, they must be loaded first before can be used.

My solution now is for types, or any file that needs to be loaded first and with a order is the next prefix:

- ```1_base_types.R```
- ```2_complex_types.R``` (this uses types defined on ```1_basetypes.R```)
- All other files

Using this prefix you can load the files in a safe way, I use Linux, no idea of R uses other way to load libs on Mac or Windows.

Thx!

**Comment by moodymudskipper** [comment]
This wouldn't be a problem after #35 (use only assertion factories, not assertions) though would it ?
Can you share a reproducible example (preferably written here, no zip file), because the only way I see it being a problem is if you define a new **function** type and want to use it in a script before it's defined.

**Comment by latot** [comment]
Hi, yes, lets see...

R/network_types.R
```R
node_id <- function() {
  typed::Integer(anyNA = FALSE, null_ok = FALSE)
}
```

R/network_node.R
```R
reverse_node <- ? function(nodes = ? node_id) {
 rev(nodes)
}
```

This will fails, as you says ```define a new function type and want to use it in a script before it's defined.```, a difference when you do a script from a library, is the order when the files are loaded, on a script you defines that, but in a library, I found they are loaded by the alphabet, this causes if you have types defined on a file, that will be used in a lot of other files, and some of the files are loaded first, the types will not exists.

How we usually in a lib, we does not choose when to load the files this appears. Except if you tweak the file names as I wrote on the issues.

I prefer send a zip with a project, because with that you can test it directly, if you just move to a script what I wrote, then you will not be able to reproduce this.

Thx!

**Comment by moodymudskipper** [comment]
Right, indeed the types used in arguments need to be defined before the functions, that might be mentioned in a vignette "Using {typed} in packages", referenced in the README, and we can drop the package section from the too long README and reference the vignette/article from the README

**Comment by latot** [comment]
Here the solution:

https://community.rstudio.com/t/weird-execution-files-on-library-elements-not-found/174194/4?u=latot

The other solution, is have an extra package with the lib types.

**Comment by moodymudskipper** [comment]
Thanks, I'll mention @include in the doc, it's the most elegant solution

**Comment by moodymudskipper** [comment]
Follow up in #53
