### ISSUE TITLE
[Feature Request] Stronger types

### ISSUE THREAD

**Issue by latot** [moodymudskipper/typed#44]
Hi all again!, here again, hopes I'm not being too annoying.

Now, that I think I have learned the basics, and I'm able to use at minimum the typed on libraries, I have noticed there is a type that would be great to use.

Strong typing has at least, two focus.

- A specific type have a specific type of data
- When there is a var declared  with a specific type, you can only use that type, even if the content is still valid by the previous focus

The first one, is the already implemented one ```typed::Data.frame``` or ```typed::Integer()``` force and checks the var to have the same type of content, or keep the properties of the data in order to have everything valid.

What I think would be great to have too, would be the second one too, specially for libraries.

There is several ways to focus for that approach, I'll just clarify what I mean.

```R

type_node <- function() typed::Integer()
type_value <- function() typed::Integer()

type_f <. function() typed::Data.frame()

f <- type_f() ? function(nodes = ? type_node(), values = ? type_value()) {
 data.frame(node = nodes, value = value)
}

type_node ? nodes <- as.integer(1:10)
type_value ? values <- as.integer(11:20)

#This will works
f(nodes, values)

#This also works, ideally not to works
#because the params does not use the same assertion types
f(values, nodes)
```

The point, is to match in some way the assertion types to be the same, so even if the content is the same, if the type of the value are different, ideally to just don't works, is like when in C++ you have two structs with different names, but with the same internal vars, even if they are the same internally, you can't use two different structs.

There is a lot of ways to solve this to handle, maybe you can have a better idea, in my case I think for example something like ```typed::Integer(name = "type_node")``` and use the names to compare the different vars.

This can have its extra benefits too, if you set a param from a value that does not have any assertions, you need to check if the values are valid with the assertions, but, if you have two vars with exactly the same type, you don't need to check the assertions because is already valid, in case they have different assertions you can says they are not valid, without check the content assertions too.

Well, that last phrase is assuming you can know the assertion from the values, no idea if this can be done.

Thx!

**Comment by moodymudskipper** [comment]
If you want nodes and values to be different things I think you should give them a different class and have an appropriate type definition, something like : 

``` r
library(typed)
#> 
#> Attaching package: 'typed'
#> The following object is masked from 'package:utils':
#> 
#>     ?

type_node <- function() typed::Integer(class = c("integer", "node"))
type_value <- function() typed::Integer(class = c("integer", "value"))

type_f <- function() typed::Data.frame()

f <- type_f() ? function(nodes = ? type_node(), values = ? type_value()) {
  data.frame(node = nodes, value = values)
}

type_node() ? nodes <- structure(1:10, class = c("integer", "node")) 
# or define a helper and `type_node() ? nodes <- node(1:10)`
type_value() ? values <- structure(11:20, class = c("integer", "value"))

# works
f(nodes, values)
#>    node value
#> 1     1    11
#> 2     2    12
#> 3     3    13
#> 4     4    14
#> 5     5    15
#> 6     6    16
#> 7     7    17
#> 8     8    18
#> 9     9    19
#> 10   10    20

# doesn't work
f(values, nodes)
#> Error: In `f(values, nodes)` at `check_arg(nodes, type_node())`:
#> wrong argument to function, `class` mismatch
#> `class(value)`: "integer" "value"
#> `expected`:     "integer" "node"
```

Regarding redundant assertions when a type is already validated, there might be something we can do, with a variation of https://twitter.com/search?q=%40antoine_fabri%20attributes&src=typed_query
I don't want types to modify the values returned by the active bindings, but we can use this hidden attribute trick to store the type and skip assertions if we retrieve it. This comes with an overhead of itself though so we'd have to see how cheap it is.

**Comment by latot** [comment]
:O that is nice workaround.

I feel not very friendly to use, the ```structure``` requires to have at least, all the classes of the object, then add a custom one, I have tested with custom assertions and works which is great.

I agree change the actual values are not great to do.

I think the hidden param would be the best choice, the reason is the workflow.

When a param goes inside a function, is not great to request a user to use struct, so it should not use struct, and then inside the function redefine the variable with struct, which is pretty simple.

The hard part would be the out of the function.

In one hand, for a normal user is not great to have struct, change the classes for a normal user can have more consequences, if the user wants to sum integers with float, or two integers for a new workflow the struct can block it without a reason.

The second one, if we choose to not use structs in the out of the function, that would cause to not be able to check the types for functions that works inside scripts or libraries.

So the hidden variable, I think is the best option.

**Comment by latot** [comment]
Hi, sorry, seems I'm not being able to explain very well.

I agree the idea is not replace the class system.

And lets put this clear, is not the same develop a library, something that will be public to personal scripts, what I tried to wrote affects more when you want to do something public.

Lets show examples, seems to works better for this explanations:

```R

node <- function(x) {
  structure(x, class = c("integer", "node"))
}

is_node <- function(x) {
  inherits(x, "node")
}

Node <- function() typed::Integer(is_node = TRUE)

fun <- ? function(nodes = ? Node()) {
  rev(nodes)
}
```

With this the first issue comes here, imagine you will publish ```fun```, so the user comes and want to use it:

```R
fun(1:10)
Error: In `fun(1:10)` at `check_arg(nodes, Node())`:
wrong argument to function, `is_node` mismatch
`is_node(value)`: FALSE
`expected`:       TRUE
```

This was the first case I wrote above, the normal user will not be able to use it, ```Node()``` must works internally on a library, but the restrictions should not be passed to the user.

Then the workaround:

```R
node <- function(x) {
  structure(x, class = c("integer", "node"))
}

is_node <- function(x) {
  inherits(x, "node")
}

Node <- function() typed::Integer(is_node = TRUE)

user_Node <- function() typed::Integer()

fun <- ? function(nodes = ? user_Node()) {
  Node() ? nodes <- node(nodes)
  rev(nodes)
}
```

(The code does not works, I have found a  new bug there D:)

What is the point in this new function, everything will works with the types, but the output will have a class of ```c("integer", "node")```, which is also something that should not happens.

The new fix for that would be set again the output with the type:

```R
user_node <- function(x) {
  structure(x, class = c("integer"))
}
fun <- ? function(nodes = ? user_Node()) {
  Node() ? nodes <- node(nodes)
  user_node(rev(nodes))
}
```

With that, the input data is friendly with the user, and the output too.

Oks, until now was 2/3 parts I described above, the last one, and why ```struct``` is not ideal for this checks, is when the functions are public but you also need to use them internally, which is reasonable.

```R
fun2 <- ? function(nodes = ? Node()) {
  nodes <- fun(nodes)
  nodes
}
```

What happens here, is that how to the output data to be used by the user, we have cleaned the classes, but that causes that ```fun2``` now will not works, because ```fun``` does not return a ```Node``` type, in first place ```fun``` and ```fun2``` should return a ```Node``` type/assertion (```Node() ? fun```).

So, putting all that to the mix, try to use ```struct``` forces you to, be not user friendly or just skip the type check on the whole library you want to write.

On the other side, store the hidden value and use it to compare, not just speed up some sections, it also keeps the classes clean, user friendly, and a lot easier to use!

Too much text! Hope I was able to explain it well, at least my intention is help to improve the lib with the feedback :)

Thx!

**Comment by moodymudskipper** [comment]
tbh I'm not fully following you, it seems you don't want your object to have a class, but you want it to be recognised as a node anyway. If you want your node objects to be special they really need a class.



``` r
library(typed)
#> 
#> Attaching package: 'typed'
#> The following object is masked from 'package:utils':
#> 
#>     ?
node <- function(x) {
  structure(x, class = c("integer", "node"))
}

is_node <- function(x) {
  inherits(x, "node")
}

Node <- function() typed::Integer(is_node = TRUE)

fun <- ? function(nodes = ? Node()) {
  rev(nodes)
}

# this is expected to fail, the type provided is not good :
# we want a node, you provide an integer, we refuse regular integers just like we'd refuse other types of integers (of class "value" for instance) 
fun(1:10)
#> Error: In `fun(1:10)` at `check_arg(nodes, Node())`:
#> wrong argument to function, `is_node` mismatch
#> `is_node(value)`: FALSE
#> `expected`:       TRUE

# this works however
fun(node(1:10))
#>  [1] 10  9  8  7  6  5  4  3  2  1

x <- node(1:10)
fun(x)
#>  [1] 10  9  8  7  6  5  4  3  2  1
```

<sup>Created on 2023-09-28 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Ideally `rev()` should return a node too, but this is not {typed} 's responsibility, you have to maintain your classes, you can define a S3 class:

```
rev.node <- function(x) {
  node(NextMethod(x))
}

fun(node(1:10))
#>  [1] 10  9  8  7  6  5  4  3  2  1
#> attr(,"class")
#> [1] "integer" "node"
```

Or you can use {vctrs} to get classes so you don't have to manually worry about those

``` r
library(typed)
#> 
#> Attaching package: 'typed'
#> The following object is masked from 'package:utils':
#> 
#>     ?
node <- function(x) {
  vctrs::new_vctr(x, class = "node")
}

is_node <- function(x) {
  inherits(x, "node")
}

Node <- function() typed::Integer(is_node = TRUE)

fun <- ? function(nodes = ? Node()) {
  rev(nodes)
}

fun(node(1:10))
#> <node[10]>
#>  [1] 10  9  8  7  6  5  4  3  2  1
```

<sup>Created on 2023-09-28 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by moodymudskipper** [comment]
I'd rather close this, it's too complex and confused, if something is still needed please reopen a single focused idea.
