### ISSUE TITLE
Can't redefine declarations inside a function

### ISSUE THREAD

**Issue by latot** [moodymudskipper/typed#45]
Hi all!

```R
library(typed)

fun <- ? function(nodes = Integer()) {
  Double() ? nodes <- as.double(nodes)
  nodes
}

fun(1:10)

rror in makeActiveBinding(x, f, pf) : 
  symbol already has a regular binding
```

While outside a function it works:

```R
Integer() ? nodes <- 1:10
Double() ? nodes <- as.double(nodes)
```

Thx!

**Comment by moodymudskipper** [comment]
In the first case you're declaring a variable but it already exists  and was not declared (in the {typed} sense, in the second case you declare it two times, so it's a bit different. Though I understand the confusion.

I'm not sure if I should act on this (or if I can), maybe the 2nd case should fail too.
I'm not sure associating a binding to 2 different types successively in the function is a good idea. better create `nodes_dbl` I think, and I think it's good that the code forces you to do it.

FWIW this would work (and maybe shouldn't): 

```
fun <- ? function(nodes = ?+ Integer()) {
  Double() ? nodes <- as.double(nodes)
  nodes
}

fun(1:10)
#>  [1]  1  2  3  4  5  6  7  8  9 10
```

**Comment by latot** [comment]
I have the same question... no idea if is the best be able to redefine that way, I know redefine like that is pretty bad, at the same times in R you some times needs to change the var types several times...

I did that change thinking.. the user has some input thing, now I need to be sure it has the right type, that is why I was declaring it again, it is reasonable in R do that, but not that much after that.

**Comment by moodymudskipper** [comment]
I changed my mind on this, I just allowed it. This way I don't break code and I'm consistent

**Comment by latot** [comment]
Hi!, I was going to write, I think this would be allowed too, in a string typed language is not ideal, but in R we dno't have strong types and we lack of a lot of tools that a language like c++/typescrypt/rust would give to use to handle several types of data, constructing new data/types to keep all in order.

For example, a dataframe is pretty common to add a new columns to it, we would need to change the assertion of it with each workflow, why not write new elements? there is mainly two reasons I have in mind now, one R is pretty bad handling a lot of data, that can cause data duplication in a lot of places, which can cause a lot of problems with Ram, the other one is organization, keep new columns can be pretty complex when we want to operate with libraries like dplyr.

Thx!
