### ISSUE TITLE
Return fails when using local inside a function and if the variable is typed

### ISSUE THREAD

**Issue by latot** [moodymudskipper/typed#47]
Hi all, this is pretty similar to https://github.com/moodymudskipper/typed/issues/40

The difference here, is that if the assignment of local is to a variable that has a type, the error happens again.

```R
library(typed)

f <- typed::Integer() ? function() {
 
 typed::Double() ? foo <- local({
  return(as.double(1))
 })

 return(as.integer(1))
}

f()
Error: In `f()` at `declare("foo", typed::Double(), value = local({     return(check_output(as.double(1), typed::Integer())) }))`:
In `eval(quote({     return(check_output(as.double(1), typed::Integer())) }), new.env())` at `check_output(as.double(1), typed::Integer())`:
wrong return value, type mismatch
`typeof(value)`: "double" 
`expected`:      "integer"
```

Thx!

**Comment by moodymudskipper** [comment]
Can you still reproduce it with the current version ? I can't

**Comment by latot** [comment]
Hi!, you are right, this is fixed on git, but not in the latest release.

Maybe you want to add this to the lib tests? I like tests :)
